[project]
name = "avion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vasyl Rapynets", email = "rapinecvasiliy@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
avion = "avion:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
